repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    # -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-json
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        # args: [--py312-plus, --add-import, 'from __future__ import annotations']
        args: [--py312-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        args: [--max-line-length, '180',--in-place]
# -   repo: https://github.com/psf/black
#     rev: 24.10.0
#     hooks:
#     - id: black
#       language_version: python3.12
#       args: [-l 180]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [--remove-unused-variables,--remove-all-unused-imports,--in-place,--expand-star-imports,--remove-duplicate-keys,--remove-unused-variables]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=180,'--ignore=F541,W503']
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.13.0
#     hooks:
#     -   id: mypy
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.10
#     hooks:
#     - id: bandit
#       args: [-ll]
